language: php

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files

## PHP versions we test against
php:
  - 7.2
  - 7.3
  - nightly

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: 7.2
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=lowest
    - php: nightly
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=highest
    - php: 7.3
      env: dependencies=highest
    - php: nightly
      env: dependencies=highest

## Update composer and run the appropriate composer command
before_script:
  - composer self-update -q
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - composer show -i

## Run the actual test
script: make travis

after_script: make travis-coverage
